services:
    database:
        image: mysql:latest
        environment:
           -MYSQL_ALLOW_EMPTY_PASSWORD='YES'
           -MYSQL_DATABASE=db_springboot_backend

        ports:
            - "5432:5432"

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
             - SPRING_DATASOURCE_ULR=jdbc:mysql://clientes_db:3306/db_springboot_backend
             - SPRING_DATASOURCE_USERNAME=root
             - SPRING_DATASOURCE_PASSWORD=

        depends_on:
            - database

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "80:80"
        depends_on:
            - backend

    nginx:
        image: nginx:latest
        volumes:
            - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "85:80"
